### ISSUE TITLE
Error on DirectCheckout.initialize

### ISSUE THREAD

**Issue by lcsvcn** [tamojuno/direct-checkout-android#3]
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.guincho7.customer, PID: 32517
>     java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit$Builder;
>         at br.com.juno.directcheckout.api.ApiFactory.makeRetrofitService(JunoApi.kt:32)
>         at br.com.juno.directcheckout.DirectCheckout.loadPublicKey(DirectCheckout.kt:134)
>         at br.com.juno.directcheckout.DirectCheckout.initialize(DirectCheckout.kt:38)
>         at br.com.juno.directcheckout.DirectCheckout.initialize$default(DirectCheckout.kt:32)
>         at com.guincho7.payment.Juno.<init>(Juno.kt:15)
>         at com.guincho7.customer.PaymentActivity.onCreate(PaymentActivity.kt:49)
>         at android.app.Activity.performCreate(Activity.java:7136)
>         at android.app.Activity.performCreate(Activity.java:7127)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6762)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>      Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.Retrofit$Builder" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.guincho7.customer-Q9sYnzjvZBN6OXlX3RT-hg==/base.apk"],nativeLibraryDirectories=[/data/app/com.guincho7.customer-Q9sYnzjvZBN6OXlX3RT-hg==/lib/arm64, /data/app/com.guincho7.customer-Q9sYnzjvZBN6OXlX3RT-hg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         at br.com.juno.directcheckout.api.ApiFactory.makeRetrofitService(JunoApi.kt:32) 
>         at br.com.juno.directcheckout.DirectCheckout.loadPublicKey(DirectCheckout.kt:134) 
>         at br.com.juno.directcheckout.DirectCheckout.initialize(DirectCheckout.kt:38) 
>         at br.com.juno.directcheckout.DirectCheckout.initialize$default(DirectCheckout.kt:32) 
>         at com.guincho7.payment.Juno.<init>(Juno.kt:15) 
>         at com.guincho7.customer.PaymentActivity.onCreate(PaymentActivity.kt:49) 
>         at android.app.Activity.performCreate(Activity.java:7136) 
>         at android.app.Activity.performCreate(Activity.java:7127) 
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905) 
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at android.app.ActivityThread.main(ActivityThread.java:6762) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

`package com.guincho7.payment

import android.content.Context
import android.text.TextUtils
import android.util.Log
import br.com.juno.directcheckout.DirectCheckout
import br.com.juno.directcheckout.model.Card
import br.com.juno.directcheckout.model.DirectCheckoutException
import br.com.juno.directcheckout.model.DirectCheckoutListener

class Juno(context : Context, production : Boolean) {
    private val TAG : String = "DEVS"

    init {
       DirectCheckout.initialize(context, production)
    }

    fun createCreditCard(card : CreditCard, callback : CreditCardCallback) {
        val card = Card(
            cardNumber = card.number.toString(),
            holderName = card.name.toString(),
            securityCode = card.cvc.toString(),
            expirationMonth = card.month.toString(),
            expirationYear = card.year.toString()
        )

        if(!(card.validateNumber() and card.validateCVC() and card.validateExpireDate())) {
            Log.d(TAG, "createCreditCard - Extra verification, card is not valid")
            return
        }

        DirectCheckout.getCardHash(card, object : DirectCheckoutListener<String> {

            override fun onSuccess(cardHash: String) {
               callback.onSuccess(cardHash)
            }

            override fun onFailure(exception: DirectCheckoutException) {
                callback.onFailure()
            }
        })

    }

    fun checkCreditCard(card : CreditCard) : CreditCardVerification {
        val verification = CreditCardVerification(
            number = false,
            name = false,
            cvc = false,
            month = false,
            year = false
        )

        verification.number = DirectCheckout.isValidCardNumber(card.number.toString())
        verification.name = DirectCheckout.isValidCardNumber(card.name.toString())
        verification.cvc = DirectCheckout.isValidCardNumber(card.cvc.toString())
        verification.month = DirectCheckout.isValidCardNumber(card.month.toString())
        verification.year = DirectCheckout.isValidCardNumber(card.year.toString())

        return verification
    }

    data class CreditCard(
        var number: String?,
        var name: String?,
        var cvc: String?,
        var month: String?,
        var year: String?
    )

    data class CreditCardVerification(
        var number: Boolean,
        var name: Boolean,
        var cvc: Boolean,
        var month: Boolean,
        var year: Boolean
    )
}`

Error instantiate class

Calling juno = Juno(this, false) from the right Activity (Payment Activity)

**Comment by diefferson** [comment]
Are you using Proguard?  

Try add this in proguard file:

-keep class br.com.juno.** { *; }

**Comment by lcsvcn** [comment]
Hello, I am using the default config.

Add this to Proguard and still give same error.

I have add to module proguard file and to app proguard file. Without success

**Comment by lcsvcn** [comment]
If I comment the line: DirectCheckout.initialize(context, production) the activity opens - Without error. But if I try to create card it say that need to be initialized before.

**Comment by diefferson** [comment]
You are calling DirectCheckout.initialize(context, production) inside the  ```init {}``` block? is necessary add in onCreate on Activity or another lifecycle method after this.

**Comment by lcsvcn** [comment]
There is no reason for that be the reason of the error.

I found out that the lib is not handling dependencies well.

I had this into my gradle:

>     implementation 'com.squareup.retrofit2:retrofit:2.6.0'
>     implementation 'com.squareup.retrofit2:converter-moshi:2.6.0'

and give another error:

 ```

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.guincho7.customer, PID: 23158
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at br.com.juno.directcheckout.DirectCheckout.loadPublicKey(DirectCheckout.kt:135)
        at br.com.juno.directcheckout.DirectCheckout.initialize(DirectCheckout.kt:38)
        at br.com.juno.directcheckout.DirectCheckout.initialize$default(DirectCheckout.kt:32)
        at com.guincho7.payment.Juno.<init>(Juno.kt:14)
        at com.guincho7.customer.PaymentActivity.onCreate(PaymentActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" on path: DexPathList[[zip file "/data/app/com.guincho7.customer-HLNeA6HuI1oTzVa48NlHmw==/base.apk"],nativeLibraryDirectories=[/data/app/com.guincho7.customer-HLNeA6HuI1oTzVa48NlHmw==/lib/x86, /data/app/com.guincho7.customer-HLNeA6HuI1oTzVa48NlHmw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at br.com.juno.directcheckout.DirectCheckout.loadPublicKey(DirectCheckout.kt:135) 
        at br.com.juno.directcheckout.DirectCheckout.initialize(DirectCheckout.kt:38) 
        at br.com.juno.directcheckout.DirectCheckout.initialize$default(DirectCheckout.kt:32) 
        at com.guincho7.payment.Juno.<init>(Juno.kt:14) 
        at com.guincho7.customer.PaymentActivity.onCreate(PaymentActivity.kt:49) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by lcsvcn** [comment]
The workaround to this bug is to add this lines before import your lib

> implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1'
> implementation 'com.squareup.retrofit2:retrofit:2.6.0'
> implementation 'com.squareup.retrofit2:converter-moshi:2.6.0'

These dependencies should be handled by the Juno lib, but there is something mess up so it does not found any of them.

> implementation "br.com.juno:directcheckout:0.0.2"

It would be nice if it should be fixed to a new release. Also I check that the version used in this lib is not up-to-date

**Comment by viini42** [comment]
> The workaround to this bug is to add this lines before import your lib
> 
> > implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1'
> > implementation 'com.squareup.retrofit2:retrofit:2.6.0'
> > implementation 'com.squareup.retrofit2:converter-moshi:2.6.0'
> 
> These dependencies should be handled by the Juno lib, but there is something mess up so it does not found any of them.
> 
> > implementation "br.com.juno:directcheckout:0.0.2"
> 
> It would be nice if it should be fixed to a new release. Also I check that the version used in this lib is not up-to-date

I had the same problem, but even with this workaround, I had to add the okhtpp library, resulting in this gradle dependencies:
```groovy
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
implementation 'com.squareup.retrofit2:converter-moshi:2.6.0'
implementation 'com.squareup.retrofit2:retrofit:2.7.2'
implementation 'com.squareup.okhttp3:okhttp:4.5.0'
implementation 'br.com.juno:directcheckout:0.0.2'
```
> PS: the okhttp 4.6.0 shows an [issue](https://github.com/square/okhttp/issues/5760)

**Comment by diefferson** [comment]
@lcsvcn  e @viniciusalmada this bugs is fixed in last release
